### ISSUE TITLE
I couldn't make it work

### ISSUE THREAD

**Issue by oturan233** [xadamxk/MMM-LOLESPORTS-SCHEDULES#3]
Hi,

I tried following commands :

git clone https://github.com/xadamxk/MMM-CHAMPIONSQUEUE-LEADERBOARD.git
cd MMM-CHAMPIONSQUEUE-LEADERBOARD/
npm install

and added the following lines to config.js

        {
                module: "MMM-LOLESPORTS-SCHEDULES",
                position: "bottom_center",
                config: {       showPeriodLabel: false,
        use24HourTime: true,
        useTeamFullName: true,
        showTournamentBlock: true}
        },

module does not appear on the mirror.

I have many modules that works, do I miss something?

Thanks.

**Comment by xadamxk** [comment]
@oturan233 Updated the readme. Follow the new instructions and reply back if you run into any issues.

The clone link I included was for champions queue, not this schedules module.

**Comment by oturan233** [comment]
It worked thanks
