### ISSUE TITLE
leagueId does not work

### ISSUE THREAD

**Issue by oturan233** [xadamxk/MMM-LOLESPORTS-SCHEDULES#4]
Hi ,

Thanks for this great module..

When I try to set leagueId for LCK

        leagueId:"98767991310872058",

nothing appears.

If I delete league ID NA LCS appears.

I tried several version for this but it does not work for example

 leagueId:98767991310872058,

 leagueId:'98767991310872058',

 leagueId:"lck",

**Comment by xadamxk** [comment]
`leagueId` is an array of strings, so something like this should work for the LCK:
```JSON
{
   "module":"MMM-LOLESPORTS-SCHEDULES",
   "position":"bottom_left",
   "config":{
      "leagueId":[
         "98767991310872058"
      ]
   }
}
```

For example, if you wanted multiple leagues (LCK + LCS):
```JSON
{
   "module":"MMM-LOLESPORTS-SCHEDULES",
   "position":"bottom_left",
   "config":{
      "leagueId":[
         "98767991310872058",
         "98767991299243165"
      ]
   }
}
```

**Comment by oturan233** [comment]
It worked, 

Thanks again..
